added proxies param to API, for trickle down into requests
Geotab/mygeotab-python pull request #327
Opened 2020-10-21 19:51 UTC by Softyy

I work behind a corp firewall, and need to pass proxy info to requests module without using env vars. This just adds an extra param to the constructor for API to allow proxy info to be passed in following requests format.

2020-11-10 13:57 UTC, sahilyahiya commented
@Softyy  Could you please let me know how can I pass proxy information in my python script. I have updated my api.py as per your    new update.

api = mygeotab.API(username='uname', password='pass', database='dbname' ,proxies="proxyipandport")


I am using above syntax to for passing proxyURL however its throwing following error, once I run my script.

TypeError: __init__() got an unexpected keyword argument 'proxies'

2020-11-10 14:31 UTC, Softyy commented
I forgot to add the param to the python3 constructor, it's there now.

2020-11-10 14:54 UTC, sahilyahiya commented
Thanks for the great support @Softyy . Its working now

2020-11-21 01:10 UTC, aaront requested changes
Thanks for your PR! Think it looks good, just a few minor style suggestions.

2020-11-21 01:10 UTC, aaront commented on mygeotab/api.py
> +            result = _query(self._server, method, params, self.timeout, verify_ssl=self._is_verify_ssl,proxies=self._proxies)
Just some minor formatting here, can you add a space before `proxies=...`? Thanks!

2020-11-21 01:10 UTC, aaront commented on mygeotab/api.py
> +            result = _query(self._server, "Authenticate", auth_data, self.timeout, verify_ssl=self._is_verify_ssl,proxies=self._proxies)
Same thing here, can you add a space before `proxies=...`? Thanks!

2020-11-21 01:10 UTC, aaront commented on mygeotab/api.py
> +    return _query(server, method, parameters, timeout=timeout, verify_ssl=verify_ssl,proxies=proxies)
Same thing here, can you add a space before `proxies=...`? Thanks!

2020-11-21 01:10 UTC, aaront commented on mygeotab/py3/api_async.py
> +        self, username, password=None, database=None, session_id=None, server="my.geotab.com", timeout=DEFAULT_TIMEOUT,proxies=None
Same thing here, can you add a space before `proxies=...`? Thanks!

2020-11-21 01:10 UTC, aaront commented on mygeotab/py3/api_async.py
> +        super().__init__(username, password, database, session_id, server, timeout,proxies=proxies)
Same thing here, can you add a space before `proxies=...`? Thanks!

Also, can you add the docstring for this?

2020-11-21 01:10 UTC, aaront commented on mygeotab/api.py
> +    :param proxies: Passes param to underlying requests package for those behind firewalls.
Please change to `The proxies dictionary to apply to the request.`

2020-11-21 01:10 UTC, aaront commented on mygeotab/api.py
> +    :param proxies: Passes param to underlying requests package for those behind firewalls.
Please change to `The proxies dictionary to apply to the request.`

2020-11-21 01:10 UTC, aaront commented on mygeotab/api.py
> +        :param proxies: Passes param to underlying requests package for those behind firewalls.
Please change to `The proxies dictionary to apply to the request.`

2020-11-21 04:11 UTC, Softyy commented
The updates have been made.

2020-11-22 21:21 UTC, aaront approved these changes

2020-11-22 21:22 UTC, merged